### ISSUE TITLE
Error : Division_by_zero

### ISSUE THREAD

**Issue by lyrm** [ocaml-sf/learn-ocaml#47] opened 2018-07-04 09:37 UTC
Two issues : 
- the header of this error is written in french (Erreur Interne)

- this error occurs very often when working on the grader but is absolutely not informative. Here are two cases I have seen it occurs : 
  * when the solution function is needed but is missing in the solution.ml file. However sometimes the right error is raised (can't found a solution) and written in the report. I did not manage to determine why I have the right error sometimes and not in other cases.
  * when I test an exercise on the platform (do the exercise and grade it), then make some changes in the test.ml file (not minors one, for example when I remove a complete test section). If I reload the exercise (without resetting my session), I have a division by zero error.

**Comment by AltGr** [comment] 2018-07-05 12:48
> the header of this error is written in french (Erreur Interne)

This is only the case because your browser is set to French, and matches the rest of the UI; why do you consider it a problem ?

> `Division_by_zero`

This is probably as dumb as computing the score % with a max score that happened to get down to 0 ? I don't think there are many more divisions happening in the code actually ;)

I could not reproduce yet though, you specified the circumstances but not the actual triggering action.

**Comment by AltGr** [comment] 2018-07-06 15:59
Should be fixed, thanks for reporting!

**Closed by AltGr** 2018-07-06 15:59 UTC
