### ISSUE TITLE
Litle bug on learn-ocaml-client cli

### ISSUE THREAD

**Issue by leunam217** [ocaml-sf/learn-ocaml#265] opened 2019-06-12 09:56 UTC
Hi, when setting options (token and server) the first time (where there is not a config file) an error is showed. But when there is already a config file exit code is 0.

![Captura de pantalla -2019-06-12 11-52-07](https://user-images.githubusercontent.com/38218036/59341924-10f19280-8d09-11e9-9dec-570b4425299c.png)

**Comment by nobrakal** [comment] 2019-06-13 07:59
I think we can close this, this bug becomes irrelevant (and I cannot reproduce it) after the merge of #267 .

**Closed** 2019-06-13 09:06 UTC
