### ISSUE TITLE
Feat: Release a new version (0.13 ?) to update docker image

### ISSUE THREAD

**Issue by asere** [ocaml-sf/learn-ocaml#417] opened 2021-09-13 15:40 UTC
> Related issue(s) or PR(s): None
> Related project scope(s) (ex: client, CSS, grading, etc...) : Docker
> Related user(s): teachers of Learn-OCaml-Essok

## The problem

Actually, we use the [learn-ocaml-corpus](https://github.com/acamanes/learn-ocaml-corpus) made by Mr.Alain in [learn-ocaml-essok](https://github/ocaml-sf/learn-ocaml-essok). Unfortunately, theses exercises do not work with Learn-OCaml v0.12 (I think this is due to conception of new exercises using the last version of Learn-OCaml).

### Wanted solution

As a solution, we will need a new release, that way we can update our [learn-ocaml-dockerfile](https://github.com/ocaml-sf/learn-ocaml-dockerfile) Dockerfile to make exercises work properly.

### Considered alternatives

As a workaround, I have created a custom [docker repository](https://hub.docker.com/r/asere/learn-ocaml-essok-dockerfile) (using learn-ocaml:master docker image) to make exercises working.

**Comment by erikmd** [comment] 2021-09-13 22:45
Thanks for the report! I was thinking that learn-ocaml-corpus was still compatible with `ocamlsf/learn-ocaml:0.12` …

So I tried to reproduce the issue and got this error indeed:
```
$ cd learn-ocaml-corpus
$ docker run --rm -it -v "$PWD:/repository" ocamlsf/learn-ocaml:0.12
Learnocaml v.0.12 running.
Updating app at ./www   
Cannot process exercises: Unix.Unix_error(Unix.EEXIST, "mkdir", "./www/static")  
```
− side question: do you believe you got the same error, or another one?

So, indeed we should make a release to overcome this
(in the meantime I guess you can do `FROM ocamlsf/learn-ocaml:master` in your Dockerfile, but you're right that having a new release tag would be much more stable… (BTW, I'm unsure why it was necessary for you to create another custom Docker Hub repo `asere/learn-ocaml-essok-dockerfile:master` because you might have used `ocamlsf/learnocaml-essok-dockerfile:master`))

Regarding the release, @yurug and I need to discuss a number of things for preparing the release, and we plan to video-meet soon, then when we've some news, we'll be able to comment in this issue :)

**Comment by asere** [comment] 2021-09-14 08:51
> So I tried to reproduce the issue and got this error indeed:
> 
> ```
> $ cd learn-ocaml-corpus
> $ docker run --rm -it -v "$PWD:/repository" ocamlsf/learn-ocaml:0.12
> Learnocaml v.0.12 running.
> Updating app at ./www   
> Cannot process exercises: Unix.Unix_error(Unix.EEXIST, "mkdir", "./www/static")  
> ```
> 
> − side question: do you believe you got the same error, or another one?
Yes, this is exactly the error I have.

> (in the meantime I guess you can do `FROM ocamlsf/learn-ocaml:master` in your Dockerfile, but you're right that having a new release tag would be much more stable… (BTW, I'm unsure why it was necessary for you to create another custom Docker Hub repo `asere/learn-ocaml-essok-dockerfile:master` because you might have used `ocamlsf/learnocaml-essok-dockerfile:master`))
Yes, I have thought about that. I highly prefer to avoid making PR in [learn-ocaml-dockerfile](https://github.com/ocaml-sf/learn-ocaml-dockerfile) for workarounds.

**Comment by erikmd** [comment] 2021-09-15 18:20
OK @asere! thanks for your feedback.

So @yurug and I were able to discuss today, so if everything goes smoothly… we could be able to release learn-ocaml 0.13 by the end of this week 😅

(FYI we opened a "meta-issue" to recap the remaining steps to address: #418)

**Comment by erikmd** [comment] 2021-10-06 00:26
Closed by https://github.com/ocaml-sf/learn-ocaml/pull/435

**Closed by erikmd** 2021-10-06 00:26 UTC
Labels: question, feature
